name: forecasting_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - tensorflow
  - jupyterlab        # For interactive notebooks
  - ipywidgets        # For interactive widgets
  - pip:
      # Add any PyPI-only packages here
      # Example:
      # - keras-tuner